@host = localhost:1337
// Register User
POST http://{{host}}/users/secured/createCourse HTTP/1.1
content-type: application/json
Authorization: 

{
    "title": "Introduction to Software Engineering",
    "code": "CEN3031"
}
###