@host = localhost:1337
// Edit Assignment Test
POST http://{{host}}/users/secured/editAssignment HTTP/1.1
content-type: application/json
Authorization:

{
    "title": "Test",
    "description": "Just another test assignment",
    "expPts": 0
}
###
