@host = localhost:1337
// Register User
POST https://{{host}}/users/secured/addAssignment HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImIuZ2F0b3IiLCJlbWFpbCI6ImIuZ2F0b3JAdWZsLmVkdSIsImV4cCI6MTY3NTA1NzEzMX0.mRernoEPnMDCnLSDxTEurT7IXtURj0XiIGvx2k6TJiE

{
    "title": "Test",
    "description": "This is a test assignment",
    "numPts": 10,
    "gradeWeight": 0.1
}
###