@host = localhost:1337

POST http://{{host}}/achievements/createAchievment
Content-Type: "application/json"

{
    "title":"First Blood!",
    "description":"Congratulations on completing your first assignment in Attack on College! Keep going!",
    "expPts":100
}

###