@host = localhost:1337

PUT http://{{host}}/achievements/editAchievment
Content-Type: "application/json"

{
    "title":"First Blood!",
    "description":"Just changing the description...",
    "expPts":5
}

###
