@host = localhost:3001
// Register User
POST https://{{host}}/users/user/register HTTP/1.1
content-type: application/json
    
{
    "firstName": "Testing",
    "lastName": "Testing",
    "username": "t.testing",
    "email": "t.testing@ufl.edu",
    "password": "TestPass"
}
###