@host = localhost:1337
// Register User
POST http://{{host}}/users/user/register HTTP/1.1
content-type: application/json
    
{
    "firstName": "Testing",
    "lastName": "Testing",
    "username": "t.testing",
    "email": "t.testing@ufl.edu",
    "password": "TestPass",
    "major": "Comp Sci",
    "college": "UF",
    "dob": "Feb 02 2023"
}
###