@host = localhost:1337
// Register User
POST https://{{host}}/users/user/register HTTP/1.1
content-type: application/json
    
{
    "firstName": "First",
    "lastName": "Last",
    "username": "f.last",
    "email": "f.last@ufl.edu",
    "password": "TestingPass"
}
###