@host = localhost:1337
// Register User
POST https://{{host}}/users/user/register HTTP/1.1
content-type: application/json
    
{
    "firstName": "Berta",
    "lastName": "Gator",
    "username": "b.gator",
    "email": "b.gator@ufl.edu",
    "password": "IDon'tKnowHonestly"
}
###